#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Dec 10, 2018 08:15:05 PM CET  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = XML_____DAE_Py_Gui (root)
    gui_support.init(root, top)
    root.mainloop()

w = None
def create_XML_____DAE_Py_Gui(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = XML_____DAE_Py_Gui (w)
    gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_XML_____DAE_Py_Gui():
    global w
    w.destroy()
    w = None


class XML_____DAE_Py_Gui:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 5 -weight normal -slant "  \
            "italic -underline 0 -overstrike 0"

        top.geometry("377x200+702+410")
        top.title("XML <-> DAE Py Gui")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.selFiles = Button(top)
        self.selFiles.place(relx=0.637, rely=0.45, height=33, width=95)
        self.selFiles.configure(activebackground="#d9d9d9")
        self.selFiles.configure(activeforeground="#000000")
        self.selFiles.configure(background="#d9d9d9")
        self.selFiles.configure(command=gui_support.convert)
        self.selFiles.configure(disabledforeground="#a3a3a3")
        self.selFiles.configure(foreground="#000000")
        self.selFiles.configure(highlightbackground="#d9d9d9")
        self.selFiles.configure(highlightcolor="black")
        self.selFiles.configure(pady="0")
        self.selFiles.configure(text='''Select Files''')

        self.selRoot = Button(top)
        self.selRoot.place(relx=0.08, rely=0.45, height=33, width=96)
        self.selRoot.configure(activebackground="#d9d9d9")
        self.selRoot.configure(activeforeground="#000000")
        self.selRoot.configure(background="#d9d9d9")
        self.selRoot.configure(command=gui_support.selectRoot)
        self.selRoot.configure(disabledforeground="#a3a3a3")
        self.selRoot.configure(foreground="#000000")
        self.selRoot.configure(highlightbackground="#d9d9d9")
        self.selRoot.configure(highlightcolor="black")
        self.selRoot.configure(pady="0")
        self.selRoot.configure(text='''Select Root''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.dispResults = Entry(top)
        self.dispResults.place(relx=0.08, rely=0.7,height=24, relwidth=0.806)
        self.dispResults.configure(background="white")
        self.dispResults.configure(disabledforeground="#a3a3a3")
        self.dispResults.configure(font="TkFixedFont")
        self.dispResults.configure(foreground="#000000")
        self.dispResults.configure(highlightbackground="#d9d9d9")
        self.dispResults.configure(highlightcolor="black")
        self.dispResults.configure(insertbackground="black")
        self.dispResults.configure(selectbackground="#c4c4c4")
        self.dispResults.configure(selectforeground="black")

        self.Label2 = Label(top)
        self.Label2.place(relx=0.106, rely=0.1, height=20, width=292)
        self.Label2.configure(anchor=W)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Root -> where game files are extracted to''')
        self.Label2.configure(width=292)

        self.Label2_1 = Label(top)
        self.Label2_1.place(relx=0.106, rely=0.2, height=20, width=292)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(anchor=W)
        self.Label2_1.configure(background="#d9d9d9")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Select XML file to generate DAE''')
        self.Label2_1.configure(width=292)

        self.Label2_2 = Label(top)
        self.Label2_2.place(relx=0.106, rely=0.3, height=20, width=292)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(anchor=W)
        self.Label2_2.configure(background="#d9d9d9")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Select DAE file to generate XML''')

        self.Label2_2 = Label(top)
        self.Label2_2.place(relx=0.08, rely=0.85, height=26, width=292)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#d9d9d9")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font9)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''gui by rjtwins''')

if __name__ == '__main__':
    vp_start_gui()



